name: build_and_release

on: 
    - push

# Run act: DOCKER_HOST=unix:///var/run/docker.sock act --container-architecture linux/amd64 --bind

jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
          - id: s01
            run: echo "github $ {{ github.ref_name}}"
        # set up the environment
          - run: echo "before " && ls -l

          - id: s02
            uses: actions/setup-node@v4
            with:
                node-version: 24
        
          - id: s03
            # Github actions by default does not link to the repo
            uses: actions/checkout@v5

          - run: echo "after " && ls -l

          - id: s04
            # Install angular cli
            run: npm i -g @angular/cli && npm ci

          - id: s05
            # build the application
            run: ng build

          - id: s06
            run: ls -l dist/countingbook/browser

          - id: s07
            uses: nwtgck/actions-netlify@v3.0
            with:
                publish-dir: dist/countingbook/browser
                production-deploy: true
            env:
                NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}


