name: Hello_world

# trigger
on:
    - pull_request

# one or more jobs
jobs:
    greetings:
        runs-on: ubuntu-latest
        steps:
        - id: s00
          # running some shell/bash command
          # single (>) - delete and write, double (>>) - append and add to end of file

          # create a value and pass to next step
          run: echo "CURR_DATE=$(date)" >> $GITHUB_OUTPUT
        
        - id: s01
          run: ls -al

        - id: s02
          uses: mscoutermarsh/cowsays-action@master
          with:
            # How to refer to prev steps: $ {{ steps. s01}}
            text: 'Moo Moo Cow! ${{ steps.s00.outputs.CURR_DATE }}'
            color: 'green'

